name: Pest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4]
        laravel: ["^12.0"]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - php: 8.3
            laravel: "^12.0"
            dependency-version: prefer-lowest
            testbench: 10.*
          - php: 8.3
            laravel: "^12.0"
            dependency-version: prefer-stable
            testbench: 10.*
          - php: 8.4
            laravel: "^12.0"
            dependency-version: prefer-lowest
            testbench: 10.*
          - php: 8.4
            laravel: "^12.0"
            dependency-version: prefer-stable
            testbench: 10.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "symfony/console:>=4.3.4" "mockery/mockery:^1.3.2" "nesbot/carbon:>=2.72.6" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
